site_name: Material for Mkdocs test setup

docs_dir: source

plugins:
  - awesome-pages
  - search:
      # Default search is quite bad. Try with a better token separator. Taken directly from:
      # https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-search/#+search.separator
      separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])'

theme:
  name: material
  # logo: assets/1200px-Lua-logo-nolabel-tutorial.png
  # favicon: assets/1200px-Lua-logo-nolabel-tutorial.png
  icon:
    repo: fontawesome/brands/square-github
  palette:
  - media: "(prefers-color-scheme: light)"
    scheme: default
    toggle:
      icon: material/toggle-switch-off-outline
      name: Switch to dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    toggle:
      icon: material/toggle-switch
      name: Switch to light mode
  features:
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - navigation.indexes
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - meta
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.snippets:
      base_path: includes
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tilde
  - toc:
      permalink: ⚓︎
      toc_depth: 3